services:
  app:
    build: .
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
    ports:
    - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '127.0.0.1:6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres-data:
