[project]
name = "ai-assistant"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "python-levenshtein>=0.27.1",
    "smolagents[litellm,telemetry]>=1.21.2",
    "sqlglot>=27.0.0",
    "fastapi>=0.115.14",
    "scalar-fastapi>=1.2.1",
    "uvicorn>=0.29.0",
    "redis>=6.2.0",
    "uuid>=1.30",
    "google-genai>=1.26.0",
    "matplotlib>=3.10.3",
    "numpy>=2.3.2",
    "seaborn>=0.13.2",
    "pillow>=11.3.0",
    "pandas>=2.3.1",
    "opentelemetry-sdk>=1.35.0",
    "opentelemetry-exporter-otlp>=1.35.0",
    "openinference-instrumentation-smolagents>=0.1.14",
    "langfuse>=3.2.8",
    "pywikibot>=10.3.2",
    "litellm[proxy]>=1.68.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "ruff>=0.12.1",
]

[tool.ruff]
line-length = 120
